### PR TITLE
Add beta banner

### PR DESCRIPTION
**Pull request by cbesozzi**
This PR add a sticky banner notifying that the site is in beta and asking for feedback as per issue #42 
image
and on mobile
image
Few questions:
- Button is a mailto: link. I used bgolder@codeforamerica.org. Should I change it?
- Any update for the text?
- because of the absolute position of the main content it disappear when scrolling to the end of the page. I did not want to modify it further to start addressing the usability testing bugs instead. 
Feedback @bengolder

### CODE REVIEW

**Comment by bengolder** [comment]
Thank you!

1.. We should change it to a google form #61 but my email is fine for now.
2. One idea for the text
    One idea: "Welcome! This website is an experiment.  Please give us feedback"
    - trying to not use beta (non-tech people often don't know what it means)
    - trying to give it a more enthusiastic tone.
3. I'd say unstick it. Let it scroll up and away.
4. I think default link styling (underlined text) is probably sufficient for the feedback link, to keep it visually subordinate to the main content of the site.

**Comment by cbesozzi** [comment]
2) 👍 
3) Sounds good: little caveat, the fixed positioning of the menu and content makes would require some changes in their structure to have the banner go across the whole page as it does today. If we can limit the banner to be inside the content that would be optimal and easy to remove without touching the rest. Thoughts? 
4) 👍

**Comment by bengolder** [comment]
Regarding 3: I see the dilemma now, thank you for clarifying. Sticky is the default and non-sticky is more work. I think your first instinct was correct regarding this.

A few more small style requests: can we use a black background, no drop shadow and the default text size?

**Comment by cbesozzi** [comment]
@bengolder just to clarify, non-sticky is fine as long as it does not have a to go across the whole screen see screenshot. If that looks fine, I can ship it.
image

**Comment by bengolder** [comment]
Wonderful, thank you!

**Pull request merged**
